Untested changes based on informal review
kraln/pymqttsn-broker pull request #1
Opened 2017-05-10 23:49 UTC by jamesmunns

Untested against actual mqtt-sn traffic. It runs and doesn't immediately die.

2017-05-10 23:50 UTC, jamesmunns commented on broker/message.py
> -                return false
`false` != `False`

2017-05-11 08:36 UTC, kraln requested changes
I would be interested in finding out why uvloop is broken--it's not my usage of it.

2017-05-11 08:36 UTC, kraln commented on broker/actions.py
> +    if mty in _DISPATCH:
I would like a log if the method is not handled

2017-05-11 08:36 UTC, kraln commented on broker/actions.py
> +    if mty in _DISPATCH:
(Understanding that this was not originally handled well, the cleanup makes it apparently missing)

2017-05-11 08:36 UTC, kraln commented on broker/message.py
> +    pass
Loogggggg pls

2017-05-11 09:14 UTC, jamesmunns commented on broker/message.py
> +    pass
Look where this exception gets handled at line 126. If this exception gets thrown, we log it.

https://github.com/jamesmunns/pymqttsn-broker/blob/mild-refactor/broker/message.py#L125-L127

2017-05-11 09:18 UTC, jamesmunns commented on broker/actions.py
> +    if mty in _DISPATCH:
Added log.

2017-05-11 15:14 UTC, kraln approved these changes
lgtm

2017-05-11 15:15 UTC, merged

2017-05-11 15:17 UTC, kraln commented
(I did test this against a publisher and a subscriber and it worked at least as well as it did before)